config/routes.rb
C02::Application.routes.draw do

  resources :contacts do
     collection do
        get :thanks
      end
    end

  resources :lists do
    collection do
      get :tminus
    end
  end

  resources :skits

root :to => "home#index"

  devise_for :users
  devise_for :admins

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable,:rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates_presence_of :email   
  
  validates_presence_of :name
  validates_presence_of :reason
  validates_presence_of :body

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/skit.rb
class Skit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contact }
    end
  end



  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_submission(@contact).deliver
        format.html { redirect_to(:action => 'thanks') }
        format.xml  { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.xml
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(@contact, :notice => 'Contact was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end



  def thanks
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.xml
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(contacts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
layout 'list'

  # GET /lists
  # GET /lists.xml
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lists }
    end
  end
  
  def tminus
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.xml
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.xml
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.xml
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to(@list, :notice => 'List was successfully created.') }
        format.xml  { render :xml => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.xml
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to(@list, :notice => 'List was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.xml
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/skits_controller.rb
class SkitsController < ApplicationController
  # GET /skits
  # GET /skits.xml
  def index
    @skits = Skit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  
    end
  end

  # GET /skits/1
  # GET /skits/1.xml
  def show
    @skit = Skit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @skit }
    end
  end

  # GET /skits/new
  # GET /skits/new.xml
  def new
    @skit = Skit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @skit }
    end
  end

  # GET /skits/1/edit
  def edit
    @skit = Skit.find(params[:id])
  end

  # POST /skits
  # POST /skits.xml
  def create
    @skit = Skit.new(params[:skit])

    respond_to do |format|
      if @skit.save
        format.html { redirect_to(@skit, :notice => 'Skit was successfully created.') }
        format.xml  { render :xml => @skit, :status => :created, :location => @skit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @skit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /skits/1
  # PUT /skits/1.xml
  def update
    @skit = Skit.find(params[:id])

    respond_to do |format|
      if @skit.update_attributes(params[:skit])
        format.html { redirect_to(@skit, :notice => 'Skit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @skit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /skits/1
  # DELETE /skits/1.xml
  def destroy
    @skit = Skit.find(params[:id])
    @skit.destroy

    respond_to do |format|
      format.html { redirect_to(skits_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/skits_helper.rb
module SkitsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.input :name  %>
    <%= f.input :email %>
	<%= f.input :reason, :collection =>[['Question', 'Question'],['Advertising', 'Advertising'], ['App Suggestions', 'App Suggestions'], ['Issues', 'Issues'], ['Internships', 'Internships']] %>
   <%= f.input :body, :label => "Reason of contact:"%>
  <div class="actions">
    <%= f.submit "Submit Form" %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<h1>Contact UNCO2</h1>

<%= render 'form' %>

app/views/contacts/thanks.html.erb
<div class="thank_you">
<h3> Thank You for your Submission!</h3>


<h4>We will be in contact with you if necessary. All of us at UNCO2 appreciate your interest in our software and hope you enjoy using our products. We love hearing suggestions on how we can make tminus better and more enjoyable to use.</h4>

</div>

app/views/home/index.html.erb
<div class="slider">
<a class="backward">prev</a>

<!-- container for the slides -->
<div class="images">

	<!-- first slide -->
	<div>
		<h3>tminus app</h3>

		<img src="../images/iphonecover.png" alt="Flying screens" style="float:left;margin:0 30px 20px 0" />

		<p style="font-weight:bold">

			Share the Anticipation
		</p>

		<p clas="co_font">
		Keep a list of all the events you are looking forward to. tminus tells you exactly how long you have to wait and lets your friends share in the anticipation. Count down to anything and everything! 
			</br></br><a href="http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=507726329&mt=8"><img src="../images/icon.png" ></a> Download tminus in the appstore now.</img>
		</p>

	</div>

	<!-- second slide -->
	<div>

		<h3>Create</h3>


		<img src="../images/iphonecoverb.png" alt="Flying screens" style="float:left;margin:0 30px 20px 0" />

		<p style="font-weight:bold">
			Creating timers is easy...
		</p>

		<p>
			Create and customize each of your countdowns with a fun background and set alerts for when your events begin. 
		</p>
		<p>In the opening scene of Back to the Future Marty McFly sees dozens of clocks at Doc Brown's home. Let's face it, that was awesome. Now with tminus you can have dozens of clocks, you can go into the future, you can go back in time, and you can hate manure. What? You already hated manure? Well tminus allows you to continue hating manure while anticipating or reminiscing about special events.</p>

		<p>You can also use tminus ironically. For example:</br></br>
		*tminus 3 years until so-and-so beats    you at golf.</br>

		*tminus 8 months until your husband beats you at words with friends.</br>

		*tminus 2 months since your coworker wore a clean shirt.</br>

		*tminus 2 minutes until Chuck Norris roundhouse kicks you in the face.</br></br>

		The possibilities are endless.</br>
		</p>

	</div>

	<!-- third slide -->
	<div>
		<h3>Share</h3>
			<img src="../images/iphonecoverc.png" alt="Flying screens" style="float:left;margin:0 30px 20px 0" />
		<p style="font-weight:bold">
			Share your countdowns with the world.
		</p>

		<p>
			After you create your countdown, tminus lets you share it with friends, family, or the whole world.
		</p>
		
		<p>"Clocks slay time... time is dead as long as it is being clicked off by little wheels; only when the clock stops does time come to life."</br></br>
		<b> - William Faulkner</b></p>

		<p>With all due respect to Mr. Faulkner, tminus didn't exist in his day. With the new tminus countdowns, time is alive!</p>
	</div>

</div>

<!-- "next slide" button -->
<a class="forward">next</a><p>

<!-- the tabs -->
<div class="slidetabs">
	<a href="#"></a>

	<a href="#"></a>
	<a href="#"></a>
</div>

</div>











<script language="JavaScript">
// What is $(document).ready ? See: http://flowplayer.org/tools/documentation/basics.html#document_ready
$(function() {

$(".slidetabs").tabs(".images > div", {

	// enable "cross-fading" effect
	effect: 'fade',
	fadeOutSpeed: "slow",

	// start from the beginning after the last tab
	rotate: true

// use the slideshow plugin. It accepts its own configuration
}).slideshow();
});

    $(document).ready(function(){
      $(".tweet").tweet({
        username: "uncarbonatedsw",
        join_text: "auto",
        avatar_size: 42,
        count: 3,
        auto_join_text_default: "we said,",
        auto_join_text_ed: "we",
        auto_join_text_ing: "we were",
        auto_join_text_reply: "we replied to",
        auto_join_text_url: "we were checking out",
        loading_text: "loading tweets..."
      });
    });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UNC02 Software</title>
  <%= stylesheet_link_tag :all %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script src="http://cdn.jquerytools.org/1.2.6/full/jquery.tools.min.js"></script>
<%= javascript_include_tag 'jquery.tweet.js' %>
  <%= csrf_meta_tag %>


</head>

<body>

  <div id="top-div">
    <div id="top-container">
        <img src="../images/logo">
<div class="top-right-box">		<a href="https://twitter.com/#!/uncarbonatedsw/"><img src="../images/followbutton.png"></img></a></div>

    </div>
</div>
<div id="main-container-wrapper">
  <div id="main-container">

<%= yield %>
  </div>	
 </div>
<div id="bottom-container-wrapper">
<div id="bot_container">
	<div class="bot_container_left">
	<span class="hilight"> <span class="on">DOWNLOAD</span> and <span class="on">SHARE</span></span>
	</br>
	</br>	
<a href="http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=507726329&mt=8"><img src="../images/appstore.png"></img></a><p>Download and share tminus with your friends.</p>	
</div>

      <div class="bot_container_left_middle">
 
          <span class="hilight"><span class="on">RECENT TWEETS</span></span>
       

      <div class="tweet"></div>



           </div> 

			<div class="bot_container_left">
			<span class="hilight"> <span class="on">About UNCO2</span></span>
	<p>	Uncarbonated Software is an iOS app development firm headquartered in Oklahoma City.</p>

		 </br><%= link_to image_tag( '../images/emailbutton.png'), new_contact_path %>
		</div>

		<div class="footer_container">
		&#169; 2012 Uncarbonated Software	
		</div>
</div>
</div>

</body>
</html>

app/views/layouts/list.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.css" />  
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.3.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.js"></script>
	<%= csrf_meta_tag %>
	
	</head>

	<body>

		<div data-role="page" data-theme="a">
		
	
		        <%= yield %>
		    
		   
		   

		    </div>

	</body>
	</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div data-role="fieldcontain">
     <label for="basic">Title:</label>
    <%= f.text_field :title %>
  </div>
<div data-role="fieldcontain">
     <label for="basic">Date:</label>
    <%= f.date_select :date %>
  </div>
<div data-role="fieldcontain">
     <label for="basic">Link:</label>
    <%= f.text_field :link %>
  </div>
<div class="ui-body ui-body-a">
		<fieldset class="ui-grid-a">
    <%= f.submit :class => 'ui-block-a' %>
</fieldset>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div data-role="header">
<%= link_to 'Delete', @link, :method => :delete, "data-icon" => "delete", "class" => "ui-btn-right" %>  
<h1>Editing Countdown</h1>
</div>
 
<div data-role="content">
  <%= render 'form' %>
</div>

app/views/lists/index.html.erb
<div data-role="header">
  <h1>Listing posts</h1>
<%= link_to 'Add', new_list_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
</div>
 
<div data-role="content">
  <ul data-role="listview">
    <% @lists.each do |list| %>
    <li>
      <%= link_to list.title, list %>
      <%= link_to 'edit countdown', edit_list_path(list), "data-icon" => "gear" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div data-role="header">
  <h1>New Post</h1>
</div>
 
<div data-role="content">
  <%= render 'form' %>
</div>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<div data-role="header">
  <h1><%= @list.title %></h1>
  <%= link_to 'Home', lists_url, "class" => "ui-btn-right" %>
</div>
 
<div data-role="content">
	<p>
	  <b>Title:</b>
	  <%= @list.title %>
	</p>

	<p>
	  <b>Date:</b>
	  <%= @list.date %>
	</p>

	<p>
	  <b>Link:</b>
	  <%= @list.link %>
	</p>
</div>

app/views/lists/tminus.html.erb
<div data-role="header">
  <h1>Popular Countdowns</h1>
</div>
<div data-role="content">
 <ul data-role="listview" data-dividertheme="e">   
<% @lists.each do |list| %>     
		<li><a href="<%= list.link %>" rel="external" data-ajax="false"><%= list.title %> 
	    <p class="ui-li-aside"><strong><%= list.date%></strong></p></a> 
<% end %> 	
	</li>
   </ul>
</div>
<script>

$("li").click(function(){
     window.location=$(this).find("a").attr("href");
     return false;
});

</script>

app/views/skits/_form.html.erb
<%= form_for(@skit) do |f| %>
  <% if @skit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skit.errors.count, "error") %> prohibited this skit from being saved:</h2>

      <ul>
      <% @skit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date_ended %><br />
    <%= f.date_select :date_ended %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skits/edit.html.erb
<h1>Editing skit</h1>

<%= render 'form' %>

<%= link_to 'Show', @skit %> |
<%= link_to 'Back', skits_path %>

app/views/skits/index.html.erb
<h1>Listing skits</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date ended</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skits.each do |skit| %>
  <tr>
    <td><%= skit.title %></td>
    <td><%= skit.description %></td>
    <td><%= skit.date_ended %></td>
     <% if admin_signed_in? %>
    <td><%= link_to 'Show', skit %></td>
    <td><%= link_to 'Edit', edit_skit_path(skit) %></td>
    <td><%= link_to 'Destroy', skit, :confirm => 'Are you sure?', :method => :delete %></td>
    <%end%>  
</tr>
<% end %>
</table>

<br />
 <% if admin_signed_in? %>
<%= link_to 'New Skit', new_skit_path %>
<%end%>

app/views/skits/new.html.erb
<h1>New skit</h1>

<%= render 'form' %>

<%= link_to 'Back', skits_path %>

app/views/skits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @skit.title %>
</p>

<p>
  <b>Description:</b>
  <%= @skit.description %>
</p>

<p>
  <b>Date ended:</b>
  <%= @skit.date_ended %>
</p>


<%= link_to 'Edit', edit_skit_path(@skit) %> |
<%= link_to 'Back', skits_path %>